/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IDeKnowScholarInterface extends ethers.utils.Interface {
  functions: {
    "getScholarId(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getScholarId",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getScholarId",
    data: BytesLike
  ): Result;

  events: {};
}

export class IDeKnowScholar extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IDeKnowScholarInterface;

  functions: {
    getScholarId(
      scholarAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getScholarId(address)"(
      scholarAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  getScholarId(
    scholarAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getScholarId(address)"(
    scholarAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getScholarId(
      scholarAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getScholarId(address)"(
      scholarAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getScholarId(
      scholarAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getScholarId(address)"(
      scholarAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getScholarId(
      scholarAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getScholarId(address)"(
      scholarAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
